### ISSUE TITLE
Googleマップが表示されない

### ISSUE THREAD

**Issue by honeniq** [rubykansai/kansai-ruby-community#2]
「関西 Ruby コミュニティー 紹介」のページで、Googleマップが表示されなくなっています。
Googleマップの利用にAPIキーが必須になったことが原因だと思われます。

参考: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by urimaro** [comment]
@honeniq 
OpenStreetMapを使うように改修しました。
確認してみてください。
